[package]
name = "gen_relocs"
version = "0.1.0"
edition = "2024"

[dependencies]
object = { version = "0.38", features = ["write_core"] }
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
byteorder = "1.4"
